### PR TITLE
Added numpy dependency note; replaced 1/29 "note"

### PR DESCRIPTION
**Pull request by unijohn**
(Note:  I may not be doing this pull request correctly.)

The 1/29 note was removed from my branch.  My primary concern was making a note re: numpy's addition to the Dependency list.

### CODE REVIEW

**Comment by jmgilmer** [comment]
Hi John,
  the problem with windows is Tensorflow has no windows support.
-Justin

**Comment by unijohn** [comment]
I discovered that fact this evening when I finally looked past the "munge" code.  I have access to two MacBook Pros and a couple of Linux VMs if I just have to have something in place for the "tf" phase, but I'm still wading through the munge & data parts.  

As a side note, I've replaced the **main** in (my windows branch)/munge/go_dataset_preprocessor.py to use a configuration file to store / pass application variables instead of using the command line.  It works on both Windows 7 & Mac OS 10.9.5.  I'd imagine that it will work from Linux as well if you're interested in it.

**Comment by jmgilmer** [comment]
I'll consider it, this is actually my first time taking pull requests. I'm
still learning best code practices as I'm still relatively new to
programming.

**Comment by jmgilmer** [comment]
I should caution you that I'm not sure how much additional time I plan on
spending on this project. The code as is though should be able to train on
a directory of sgf files you create with Many Faces.

**Comment by unijohn** [comment]
I understand.  No biggie.

Since I cannot handle the tf part at the moment, I can work on the "streamline the install and munging phase" part in my fork.  Once that is as easy as "Unzip, Edit Config, Run" across Windows, MacOS, and Linux installs, I will work on the GNUGo hanging aspect.

**Comment by jmgilmer** [comment]
I believe someone already fixed the gnugo issue, I haven't actually tested it myself but they added a thread.timer call.

**Pull request closed without merging**
